#! /bin/sh

bspc monitor -d I II III IV V VI VII VIII IX X 
#VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer     true

bspc config pointer_modifier          mod4
bspc config pointer_action1           move
bspc config pointer_action2           resize_side
bspc config pointer_action3           resize_corner

bspc rule -a scratch sticky=on state=floating focus=on

#exec ~/.config/bspwm/scripts/low_battery_notifier.sh

#-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

# Fix Java Applications
export _JAVA_AWT_WM_NONREPARENTING=1


#-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

#
# Launch program system
#

# launch polybar
polybar &

# Launch picom
picom &

# Launch sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

# Launch wallpaper
feh --bg-fill /home/kydo/.config/bspwm/wallpapers/sky.jpg


